modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/jowashere/WingsPort/issues"
license = "MIT"
[[mods]]
modId = "wings"
version = "${file.jarVersion}"
displayName = "Wings"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/wings-2"
authors = "toni"
description = "This is a port of the Wings mod. It introduces an assortment of avian and insectoid wings for all of your aerial travel needs."
logoFile = "logo.png"
[[dependencies.wings]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.wings]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"
